### ISSUE TITLE
Error with special characters, non ASCII.

### ISSUE THREAD

**Issue by adam-golab** [Lukasz-pluszczewski/mi18n#9]
When you call `startCase` method on a translation with diacritics, there is implicit triggered `deburr` method.

```this.props.translator.startCase().t('translationWithDiacritics');```

it returns `Aosc`, but should `Ąóść`

**Comment by Lukasz-pluszczewski** [comment]
It is directly connected with some lodash methods behaviour. [Issue](https://github.com/lodash/lodash/issues/3150) has been created.

EDIT: https://github.com/lodash/lodash/issues/3056

**Comment by Lukasz-pluszczewski** [comment]
Original [issue](https://github.com/lodash/lodash/issues/3056) has been closed, as this behaviour is intended so I'm closing this issue as well. It will change in the ver5 of lodash. mi18n will be updated to use that version as soon as it's available.
However, if you want to reimplement helper methods to avoid this issue feel free to create PR.
